# Author: Jack Hermanson
"""authorization_id_and_approval_code

Revision ID: 63fd480a724a
Revises: 
Create Date: 2025-03-02 15:34:54.318964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fd480a724a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.String(length=50), nullable=False),
    sa.Column('approval_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
